version: '3.8'

services:
  # PostgreSQL database (optional - comment out for SQLite)
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=stoic_wisdom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Use PostgreSQL (uncomment to use)
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/stoic_wisdom
      # Use SQLite (comment out to use PostgreSQL)
      # - DATABASE_URL=sqlite:/app/data/stoic_wisdom.db
      - PORT=3000
      - RUST_LOG=info
    volumes:
      - ./data:/app/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
