version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=sqlite:/app/data/stoic_wisdom.db
      - PORT=3000
      - RUST_LOG=info
    volumes:
      - ./data:/app/data
    restart: unless-stopped
