-- Update quotes with full/longer versions where applicable

-- Marcus Aurelius quotes with extended versions
UPDATE quotes SET full_text = 'You have power over your mind - not outside events. Realize this, and you will find strength. When you wake to the world each day, remember: the obstacle is the way. What stands in the path becomes the path. Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present. Our life is what our thoughts make it.' WHERE text LIKE 'You have power over your mind%';

UPDATE quotes SET full_text = 'The happiness of your life depends upon the quality of your thoughts. Therefore, guard accordingly, and take care that you entertain no notions unsuitable to virtue and reasonable nature. The nearer a man comes to a calm mind, the closer he is to strength. Remember, it is not enough to be hit or insulted to be harmed; you must believe that you are being harmed. If someone succeeds in provoking you, realize that your mind is complicit in the provocation.' WHERE text LIKE 'The happiness of your life depends%';

UPDATE quotes SET full_text = 'Waste no more time arguing what a good man should be. Be one. You could leave life right now. Let that determine what you do and say and think. Practice even what seems impossible. The left hand is useless at almost everything, for lack of practice, but it guides the reins better than the right hand because it has practice at that. Stop talking about what the good man is like, and just be one.' WHERE text LIKE 'Waste no more time arguing%';

UPDATE quotes SET full_text = 'When you arise in the morning, think of what a precious privilege it is to be alive - to breathe, to think, to enjoy, to love. Each day provides its own gifts. Begin each day by telling yourself: Today I shall be meeting with interference, ingratitude, insolence, disloyalty, ill-will, and selfishness – all of them due to the offenders'' ignorance of what is good or evil. But for my part I have long perceived the nature of good and its nobility, the nature of evil and its meanness, and also the nature of the culprit himself, who is my brother. Therefore none of these things can injure me, for nobody can implicate me in what is degrading.' WHERE text LIKE 'When you arise in the morning%';

UPDATE quotes SET full_text = 'If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it; and this you have the power to revoke at any moment. Look within. Within is the fountain of good, and it will ever bubble up, if you will ever dig. The universe is change; our life is what our thoughts make it. Very little is needed to make a happy life; it is all within yourself, in your way of thinking.' WHERE text LIKE 'If you are distressed by anything external%';

-- Seneca quotes with extended versions  
UPDATE quotes SET full_text = 'We suffer more often in imagination than in reality. It is likely that there are more things to alarm us than to harm us, and we suffer more in apprehension than in reality. What we anticipate seldom occurs, while we torment ourselves with fears of what might happen. The mind that is anxious about future events is miserable. True happiness is to enjoy the present, without anxious dependence upon the future, not to amuse ourselves with either hopes or fears but to rest satisfied with what we have, which is abundantly sufficient.' WHERE text LIKE 'We suffer more often in imagination%';

UPDATE quotes SET full_text = 'It is not that we have a short time to live, but that we waste a lot of it. Life is long enough, and a sufficiently generous amount has been given to us for the highest achievements if it were all well invested. But when it is wasted in heedless luxury and spent on no good activity, we are forced at last by death''s final constraint to realize that it has passed away before we knew it was passing. So it is: we are not given a short life but we make it short, and we are not ill-supplied but wasteful of it. Life is long if you know how to use it.' WHERE text LIKE 'It is not that we have a short time to live%';

UPDATE quotes SET full_text = 'Luck is what happens when preparation meets opportunity. Diligent preparation sets us up to seize good fortune when it arrives. For luck to find you, you must be ready. The willing are led by fate, the unwilling dragged. What we call luck is merely the intersection of readiness and circumstance. Fortune favors the prepared mind, and those who work hardest often appear to be the luckiest.' WHERE text LIKE 'Luck is what happens when%';

-- Epictetus quotes with extended versions
UPDATE quotes SET full_text = 'It''s not what happens to you, but how you react to it that matters. Events are objective and neutral; only our judgments of them have power over us. People are not disturbed by things, but by the views they take of them. When, therefore, we are hindered, or disturbed, or grieved, let us never blame anyone but ourselves; that is, our own judgments. An ignorant person is inclined to blame others for his own misfortune. To blame oneself is proof of progress. But the wise man never has to blame anyone, not even himself.' WHERE text LIKE 'It''s not what happens to you%';

UPDATE quotes SET full_text = 'There is only one way to happiness and that is to cease worrying about things which are beyond the power of our will. Some things are within our power, while others are not. Within our power are opinion, motivation, desire, aversion, and, in a word, whatever is of our own doing; not within our power are our body, our property, reputation, office, and, in a word, whatever is not of our own doing. Make the best use of what is in your power, and take the rest as it happens. The essence of philosophy is that a person should so live that their happiness depends as little as possible on external things.' WHERE text LIKE 'There is only one way to happiness%';

UPDATE quotes SET full_text = 'First say to yourself what you would be; and then do what you have to do. For in nearly every pursuit we see this to be the case: those who profess a certain discipline must labor according to that discipline. Consider this to be your first command: be consistent with yourself. Whatever you conceive yourself to be, maintain that character both publicly and when you are alone. If you would be a philosopher, let your actions speak for you. Don''t speak about your principles; embody them. The task of a philosopher: we should bring our own principles to bear on particular cases.' WHERE text LIKE 'First say to yourself what you would be%';

UPDATE quotes SET full_text = 'People are not disturbed by things, but by the views they take of them. Death, for instance, is not terrible, else it would have appeared so to Socrates; but the terror consists in our notion of death that it is terrible. When, therefore, we are hindered, or disturbed, or grieved, let us never attribute it to others, but to ourselves - that is, to our own principles. It is the action of an uninstructed person to reproach others for their own misfortunes; of one entering upon instruction, to reproach themselves; and one perfectly instructed, to reproach neither others nor themselves.' WHERE text LIKE 'People are not disturbed by things%';
