-- Insert Timeline Events
INSERT INTO timeline (year, title, description, significance) VALUES
(-300, 'Birth of Stoicism', 'Zeno of Citium founds the Stoic school in Athens, teaching from the Stoa Poikile (Painted Porch), giving the philosophy its name.', 'Marks the beginning of Stoicism as a formal philosophical school. Zeno synthesized Cynic ethics, Megarian logic, and Platonic metaphysics into a comprehensive system.'),
(-280, 'Early Development', 'Cleanthes succeeds Zeno as head of the Stoic school. The philosophy gains followers among educated Greeks and begins systematic development.', 'Cleanthes'' Hymn to Zeus becomes a classic expression of Stoic theology, emphasizing divine providence and cosmic order.'),
(-232, 'Chrysippus and Systematization', 'Chrysippus becomes third head of the Stoa and produces over 700 works, systematizing Stoic logic, physics, and ethics.', 'Chrysippus is considered the second founder of Stoicism. His logical works defend Stoic determinism and develop propositional logic. Without him, "there would be no Stoa."'),
(-155, 'Stoicism Comes to Rome', 'Diogenes of Babylon leads philosophical embassy to Rome, introducing Stoicism to Roman culture and aristocracy.', 'First major encounter between Greek philosophy and Roman pragmatism. Sets stage for Stoicism''s influence on Roman culture and law.'),
(-129, 'Panaetius Adapts Stoicism', 'Panaetius of Rhodes adapts Stoicism for Roman audiences, emphasizing practical ethics over abstract physics and logic.', 'Makes Stoicism more accessible and applicable to public life. Influences Cicero and shapes Roman Stoicism''s practical focus.'),
(-87, 'Posidonius Expands the School', 'Posidonius establishes influential Stoic school in Rhodes, integrating scientific observation with Stoic philosophy.', 'Bridges Greek and Roman Stoicism. His polymathic approach combines ethics with astronomy, geography, and history. Teaches Cicero.'),
(-44, 'Cato''s Death', 'Cato the Younger commits suicide rather than live under Caesar''s dictatorship, becoming a Stoic martyr for republican liberty.', 'Cato''s death exemplifies Stoic principles in action. His integrity and consistency make him a model of virtue in the face of political defeat.'),
(4, 'Seneca''s Birth', 'Birth of Lucius Annaeus Seneca in Corduba (Spain), who will become Rome''s most prolific Stoic writer.', 'Seneca will make Stoic philosophy accessible through letters, essays, and plays. His works bridge philosophy and practical life.'),
(50, 'Epictetus Born into Slavery', 'Birth of Epictetus in Hierapolis, Phrygia. Despite being born a slave, he will become one of the most influential Stoic teachers.', 'Demonstrates that Stoic wisdom is accessible to all, regardless of social status. His teachings emphasize inner freedom over external circumstances.'),
(62, 'Musonius Rufus Teaching', 'Musonius Rufus teaching Stoicism in Rome, mentoring Epictetus and advocating for equality including women''s education.', 'Advances progressive Stoic views on gender equality. His practical teachings influence the development of Roman Stoicism.'),
(65, 'Seneca''s Forced Suicide', 'Nero orders Seneca to commit suicide, ending the life of Rome''s greatest Stoic writer. Seneca faces death with Stoic composure.', 'Seneca''s death demonstrates his principles. His final moments, recorded by Tacitus, show courage and acceptance. His works survive and influence Western thought.'),
(75, 'Epictetus Gains Freedom', 'Epictetus gains his freedom after his master''s death and begins teaching Stoic philosophy in Rome.', 'Former slave becomes master teacher. Exemplifies Stoic teaching that true freedom is internal, not external.'),
(89, 'Exile to Nicopolis', 'Emperor Domitian expels philosophers from Rome. Epictetus moves to Nicopolis, Greece, where he establishes his famous school.', 'The exile increases Epictetus'' influence. His school attracts students from across the Empire, including future historians and leaders.'),
(121, 'Marcus Aurelius Born', 'Birth of Marcus Aurelius, future Roman Emperor and last of the "Five Good Emperors," who will become philosopher-king.', 'His future "Meditations" will preserve Stoic philosophy for posterity and demonstrate its application at the highest level of power.'),
(161, 'Philosopher Becomes Emperor', 'Marcus Aurelius becomes Roman Emperor, the closest history comes to Plato''s ideal of the philosopher-king.', 'Tests whether Stoic principles can guide supreme power. Marcus proves philosophy and leadership can coexist.'),
(167, 'Philosophy Tested by Crisis', 'Marcus Aurelius faces Antonine Plague and Marcomannic Wars while writing Meditations, applying Stoic principles during extreme adversity.', 'Shows Stoicism functioning under maximum stress: plague, war, political intrigue. Philosophy proven in the crucible of reality.'),
(180, 'End of Classical Stoicism', 'Death of Marcus Aurelius marks the end of classical Stoic philosophy and the beginning of Rome''s decline.', 'The last great Stoic philosopher. After him, Stoicism continues but produces no major new voices. His "Meditations" become the final testament.'),
(250, 'Stoicism Blends with Christianity', 'Stoic ethics increasingly influence early Christian thought through figures like Clement of Alexandria and Origen.', 'Stoic concepts like logos, cosmopolitanism, and natural law merge with Christian theology. The synthesis shapes Western ethics.'),
(529, 'Closing of Philosophical Schools', 'Emperor Justinian closes Athenian philosophical schools, ending the ancient period of Stoic teaching.', 'Formal end of ancient philosophy. However, Stoic ideas persist through Roman law, Christian ethics, and preserved texts.'),
(1584, 'Lipsius Revives Stoicism', 'Justus Lipsius publishes "De Constantia," reviving Stoicism during Renaissance and adapting it for Christian Europe.', 'Neo-Stoicism emerges. Philosophy adapted for religious context while maintaining core principles. Influences European thought.'),
(1958, 'Modern Stoicism Emerges', 'Viktor Frankl publishes "Man''s Search for Meaning," applying Stoic principles to concentration camp survival, launching modern interest.', 'Demonstrates Stoic principles'' relevance to extreme 20th-century circumstances. Influences cognitive therapy and modern self-help.'),
(1960, 'Cognitive Therapy Founded', 'Aaron Beck develops Cognitive Therapy, independently rediscovering Stoic principles that thoughts create emotions.', 'Scientific validation of ancient Stoic psychology. CBT becomes gold-standard treatment, proving Stoics were psychologically correct.'),
(2015, 'Stoicism Goes Mainstream', 'Tim Ferriss popularizes Stoicism in "Tools of Titans." Ryan Holiday''s "The Obstacle Is the Way" becomes bestseller.', 'Ancient philosophy reaches modern masses through business and self-help. Stoicism proves relevant to contemporary challenges.');

-- Insert Incidents
INSERT INTO incidents (title, philosopher_id, year, description, lesson, modern_relevance) VALUES
('Zeno''s Shipwreck', NULL, -300, 'Zeno of Citium was a wealthy merchant until a shipwreck destroyed his cargo and fortune. Washed up in Athens, he wandered into a bookshop and discovered philosophy. He later said, "I made a prosperous voyage when I suffered shipwreck."', 'Apparent disasters can redirect us to our true calling. Loss of material wealth can lead to spiritual wealth. What seems like failure may be fortune in disguise.', 'Career setbacks, financial losses, or life disruptions often redirect people to more fulfilling paths. Many successful people trace their success to apparent failures that forced new directions.'),

('Epictetus'' Broken Leg', 3, 60, 'As a slave, Epictetus'' master was twisting his leg cruelly. Epictetus calmly said, "If you keep doing that, you will break my leg." When it broke, he simply stated, "Did I not tell you that you would break it?" He showed no anger or complaint, accepting what he could not control.', 'You can maintain equanimity even during physical suffering. Your response to pain is within your control, even when the pain itself is not. Emotional composure can be maintained in any circumstance.', 'Demonstrates grace under pressure relevant to chronic pain management, medical procedures, or any unavoidable suffering. Modern pain psychology emphasizes the controllable element of pain perception.'),

('Cato''s Final Stand', NULL, -46, 'After Julius Caesar''s victory in the civil war, Cato the Younger chose death over living under tyranny. Before his suicide, he spent the evening discussing Stoic philosophy on the immortality of the soul. His calm, principled death made him a symbol of Stoic virtue and resistance to despotism.', 'Some principles are worth dying for. Personal integrity matters more than survival. How you face death reveals your character. Consistency between beliefs and actions defines authenticity.', 'While modern context rarely requires literal death for principles, the lesson applies to career sacrifices for integrity, speaking truth to power despite costs, or refusing to compromise core values for convenience.'),

('Seneca''s Exile', 2, 41, 'Emperor Claudius exiled Seneca to Corsica for eight years on charges of adultery. Rather than despair, Seneca used the time to write philosophical works including "Consolation to Helvia" and "Consolation to Polybius," turning isolation into productivity.', 'Externally imposed limitations need not limit inner development. Forced circumstances can become opportunities. Productivity and meaning can be found anywhere. Your mind is always free.', 'Applies to involuntary career interruptions, imprisonment, serious illness requiring isolation, or any forced inactivity. Many creative works were produced in quarantine, prison, or exile.'),

('Marcus'' Meditations at War', 1, 170, 'While commanding armies against Germanic tribes in brutal conditions, Marcus Aurelius wrote his "Meditations"—philosophical exercises to maintain virtue and perspective. He led military campaigns while maintaining philosophical practice, proving wisdom possible even in war.', 'Philosophy must function in the real world, not just in comfortable contemplation. Virtue can be practiced anywhere, even in extreme adversity. Leadership and wisdom can coexist.', 'Relevant to maintaining personal values in high-stress careers, ethical behavior under pressure, or spiritual practice amid demanding circumstances. Modern leaders face similar challenges balancing principle and pragmatism.'),

('Musonius Rufus'' Exile', NULL, 65, 'Exiled twice by emperors, Musonius Rufus used exile as opportunity to teach Stoicism. He said, "Exile is an opportunity to practice philosophy without distraction." He farmed, taught local students, and continued his philosophical work uninterrupted.', 'Circumstances cannot exile you from your principles. Physical location is irrelevant to philosophical practice. Adversity removes distractions, focusing on essentials. Adapt and continue.', 'Applies to unwanted relocations, job transfers, or life disruptions. Many people find that forced changes remove distractions and clarify priorities, leading to renewed focus.'),

('The Antonine Plague', 1, 165, 'During Marcus Aurelius'' reign, a devastating plague killed millions across the Roman Empire. Marcus continued his duties, maintained perspective, and wrote about accepting mortality and change. He himself likely died from the plague.', 'Even global catastrophes call for steady leadership and philosophical perspective. Accept what you cannot control (disease spread) while acting on what you can (leadership, care, order). Maintain virtue during crisis.', 'Directly relevant to COVID-19 pandemic, climate change, or any large-scale crisis. Leaders must maintain composure and effectiveness while processing the same fears as everyone else.'),

('Agrippinus'' Courage', NULL, 60, 'When Agrippinus learned he was on trial and likely to be executed or exiled, he calmly finished his meal before addressing the matter. His student asked how he could be so calm. Agrippinus replied that such things are not within his control, so why disturb himself?', 'Don''t borrow anxiety from future events. Face potential disasters with equanimity. Worrying changes nothing. Maintain composure until action is required. Peace is always an option.', 'Applies to awaiting medical test results, job interviews, legal proceedings, or any pending outcome. Anxiety during the waiting period is optional suffering that changes nothing.'),

('Helvidius Priscus'' Defiance', NULL, 70, 'The Stoic senator Helvidius Priscus repeatedly defied Emperor Vespasian, refusing to be silenced despite threats. When finally sentenced to death, he faced execution calmly, having lived according to his principles despite knowing the cost.', 'Speaking truth to power has costs, but silence has costs too. Living by principles may require accepting negative consequences. Integrity is demonstrated when it''s difficult, not when it''s easy.', 'Relevant to whistleblowers, political dissidents, or anyone risking career/safety for principle. Modern examples include journalists in authoritarian regimes or employees exposing corporate wrongdoing.'),

('Paconius Agrippinus'' Peace', NULL, 60, 'When Paconius Agrippinus was told he was being tried by the Roman Senate, he responded, "Very well, we shall make our defense." Told the trial might result in exile, he said, "Then we shall dine in Aricia" (first town on exile route). When told he might be executed, he replied, "We shall dine in Hades." He remained perfectly undisturbed by news that would terrify most people.', 'Prepare for any outcome with equanimity. Acceptance of worst-case scenarios eliminates their power over you. Tranquility comes from being ready for anything. Fear only has power when we resist outcomes.', 'Demonstrates premeditatio malorum (negative visualization) in action. Relevant to anyone facing uncertain outcomes: mentally preparing for all possibilities, including worst-case, reduces anxiety.'),

('Arria''s Stoic Death', NULL, 42, 'When Arria''s husband Paetus was ordered to commit suicide for conspiracy, he hesitated. Arria took his dagger, stabbed herself, and handed it to him saying "Paetus, it does not hurt" (Paete, non dolet). Her courage made his death easier.', 'Lead by example in facing difficulties. Courage is contagious. Show others how to face adversity. Demonstrate principles through action. Your composure can strengthen others.', 'Applies to leading family through crisis, modeling resilience for children during hardship, or maintaining composure so others can too. Parents often find strength to model courage for their children.'),

('Cleanthes'' Self-Sufficiency', NULL, -250, 'Cleanthes, second head of the Stoic school, was so poor he worked nights drawing water to support his philosophy studies by day. When other philosophers mocked his poverty, he said he was ashamed only that he couldn''t do more for Cleanthes (himself).', 'External poverty doesn''t equal internal poverty. Self-sufficiency enables philosophical pursuit. Simple living supports complex thinking. No external circumstances can stop determined learning.', 'Relevant to students working through school, career changes requiring sacrifice, or anyone pursuing meaning over money. Many successful people have periods of extreme frugality while building skills or businesses.'),

('Chrysippus'' Humility', NULL, -230, 'Chrysippus, the most prolific Stoic author, was asked why he didn''t attend the public lectures of a popular philosopher. He replied, "If I cared about the crowd, I wouldn''t be a philosopher." He focused on truth over popularity, substance over show.', 'Truth-seeking and popularity are often opposed. Focus on substance, not spectacle. Depth requires ignoring shallow attractions. Philosophical progress requires resistance to crowd approval.', 'Applies to resisting social media validation, choosing depth over virality, or pursuing unsexy but important work. Modern attention economy makes this wisdom more relevant than ever.'),

('Demonax'' Humor and Wisdom', NULL, 150, 'Demonax the Cynic-Stoic was known for using humor to teach philosophy. When asked if he believed in an afterlife, he replied, "I''m not dead yet, so I''ll let you know when I find out." His witty wisdom made philosophy accessible and enjoyable.', 'Philosophy need not be grim. Humor can convey wisdom. Take ideas seriously but not yourself seriously. Lightness and depth can coexist. Laughter and wisdom are compatible.', 'Relevant to teaching, communicating complex ideas, or maintaining perspective. Modern communicators find humor makes serious messages more digestible and memorable.'),

('Porcia''s Devotion', NULL, -43, 'Porcia, daughter of Cato and wife of Brutus, wanted to prove she could keep her husband''s secrets (about Caesar''s assassination plot). She deliberately wounded herself to demonstrate she could endure pain without revealing information. Her self-control proved her trustworthiness.', 'Self-mastery demonstrates reliability. Voluntary discomfort builds capacity for involuntary discomfort. Character is proven through tests we impose on ourselves. Strength is demonstrated, not claimed.', 'While the method is extreme, the principle applies to building discipline: voluntary challenges (cold showers, fasting, exercise) build resilience. Proving yourself to yourself matters.');
